# Generated by Django 3.2.11 on 2022-02-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220214_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('Can View Client', 'view_client')]},
        ),
    ]
