# Generated by Django 3.2.11 on 2022-02-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('view_client', 'Can View Client')]},
        ),
    ]
