version: '2'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    container_name: docker02_web
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 5555:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    container_name: docker02_db
    ports:
      - 5447:5432
    volumes:
      - Hair:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

volumes:
  Hair: