# Generated by Django 3.2.11 on 2022-01-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_booking', '0001_remove_order_barber'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
