# Generated by Django 3.2.11 on 2022-01-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_booking', '0004_alter_orderitems_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Aktivna narudzba'), ('canceled', 'Otkazana narudzba')], default='active', max_length=25, null=True),
        ),
    ]
