# Generated by Django 3.2.12 on 2022-02-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_booking', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Aktivna narudzba'), ('canceled', 'Otkazana narudzba'), ('finished', 'Završena narudzba')], default='active', max_length=25, null=True),
        ),
    ]
